### ISSUE TITLE
Stop the access controller from checking people in on foursquare constantly.

### ISSUE THREAD

**Issue by reportingsjr** [Hive13/hive-rails-access#19]
I don't know if this has been fixed, but I don't think it has! The door controller is checking at least you and me in many, many times per day.

**Comment by uid0** [comment]
The easiest way to fix this is to turn off the re-running of the resque queues when they fail.  

I'd have to figure out /why/ the resque queues are failing, though.  I'll work on it tomorrow.

**Comment by uid0** [comment]
Fixed in fbf203f1fc81ba3d535d1a1c1e5994d87f6317d8.  Closing out.
